backend:
  name: git-gateway
  branch: master

display_url: https://district.netlify.com
media_folder: static/assets/images
public_folder: /assets/images

collections:
  - name: blog
    label: Blog
    label_singular: Post
    folder: src/pages/blog
    create: true
    extension: md
    format: frontmatter
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - name: templateKey
        label: Template key
        widget: hidden
        default: blog-post
      - name: title
        label: Title
        widget: string
      - name: date
        label: Publish date
        widget: datetime
      - name: banner
        label: Banner
        widget: image
      - name: body
        label: Body
        widget: markdown
